name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Downloads code
    - uses: actions/checkout@v4

    # 2. Install Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # 3. Install Poetry
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    # 4. Install Dependencies
    - name: Install Dependencies
      run: poetry install

    # 5. Run test (Pytest)
    - name: Run Tests
      run: poetry run pytest
